CREATE TABLE IF NOT EXISTS os_platform_outbox (
 id BIGSERIAL PRIMARY KEY,
 path TEXT NOT NULL,
 payload TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 attempts INTEGER NOT NULL DEFAULT 0,
 last_error TEXT NOT NULL DEFAULT ''
);
COMMENT ON TABLE os_platform_outbox IS 'Platform 回调持久队列，按序重试，成功后删除';
ALTER TABLE os_calls ADD COLUMN IF NOT EXISTS caller TEXT NOT NULL DEFAULT '';
ALTER TABLE os_calls ADD COLUMN IF NOT EXISTS callee TEXT NOT NULL DEFAULT '';
ALTER TABLE os_calls ADD COLUMN IF NOT EXISTS agent_id TEXT NOT NULL DEFAULT '';
ALTER TABLE os_calls ADD COLUMN IF NOT EXISTS offered_agent TEXT NOT NULL DEFAULT '';
ALTER TABLE os_calls ADD COLUMN IF NOT EXISTS answered_at TIMESTAMPTZ;
